#4.1

#Task 1

In [9]:
def convert_length(value, unit):
    """
    Converts length between meters and feet.
    :param value: float, the numeric value to convert.
    :param unit: str, 'm_to_ft' for meters to feet, 'ft_to_m' for feet to meters.
    :return: float, converted value.
    """
    if unit == 'm_to_ft':
        return value * 3.28084
    elif unit == 'ft_to_m':
        return value / 3.28084
    else:
        raise ValueError("Invalid unit for length conversion.")

def convert_weight(value, unit):
    """
    Converts weight between kilograms and pounds.
    :param value: float, the numeric value to convert.
    :param unit: str, 'kg_to_lbs' for kg to lbs, 'lbs_to_kg' for lbs to kg.
    :return: float, converted value.
    """
    if unit == 'kg_to_lbs':
        return value * 2.20462
    elif unit == 'lbs_to_kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid unit for weight conversion.")

def convert_volume(value, unit):
    """
    Converts volume between liters and gallons.
    :param value: float, the numeric value to convert.
    :param unit: str, 'L_to_gal' for liters to gallons, 'gal_to_L' for gallons to liters.
    :return: float, converted value.
    """
    if unit == 'L_to_gal':
        return value * 0.264172
    elif unit == 'gal_to_L':
        return value / 0.264172
    else:
        raise ValueError("Invalid unit for volume conversion.")

def main():
    print("Unit Converter")
    print("1. Length (Meters to Feet / Feet to Meters)")
    print("2. Weight (Kilograms to Pounds / Pounds to Kilograms)")
    print("3. Volume (Liters to Gallons / Gallons to Liters)")

    try:
        choice = int(input("Select conversion type (1-3): "))
        value = float(input("Enter the value to convert: "))

        if choice == 1:
            unit = input("Enter 'm_to_ft' for meters to feet or 'ft_to_m' for feet to meters: ")
            result = convert_length(value, unit)
        elif choice == 2:
            unit = input("Enter 'kg_to_lbs' for kg to lbs or 'lbs_to_kg' for lbs to kg: ")
            result = convert_weight(value, unit)
        elif choice == 3:
            unit = input("Enter 'L_to_gal' for liters to gallons or 'gal_to_L' for gallons to liters: ")
            result = convert_volume(value, unit)
        else:
            print("Invalid choice.")
            return

        print(f"Converted value: {result:.4f}")
    except ValueError as e:
        print(f"Error: {e}")
    except Exception:
        print("An unexpected error occurred.")

if __name__ == "__main__":
    main()

Unit Converter
1. Length (Meters to Feet / Feet to Meters)
2. Weight (Kilograms to Pounds / Pounds to Kilograms)
3. Volume (Liters to Gallons / Gallons to Liters)
Select conversion type (1-3): 2
Enter the value to convert: 2
Enter 'kg_to_lbs' for kg to lbs or 'lbs_to_kg' for lbs to kg: lbs_to_kg
Converted value: 0.9072


#Task 2

In [14]:
def calculate_sum(numbers):
    """
    Calculates the sum of a list of numbers.
    :param numbers: list of floats.
    :return: float, sum of numbers.
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculates the average of a list of numbers.
    :param numbers: list of floats.
    :return: float, average of numbers.
    """
    return sum(numbers) / len(numbers) if numbers else 0

def find_maximum(numbers):
    """
    Finds the maximum number in a list.
    :param numbers: list of floats.
    :return: float, maximum number.
    """
    return max(numbers)

def find_minimum(numbers):
    """
    Finds the minimum number in a list.
    :param numbers: list of floats.
    :return: float, minimum number.
    """
    return min(numbers)

def main_math_operations():
    print("Mathematical Operations")
    try:
        numbers = input("Enter a list of numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]
        print("Choose an operation: sum, average, max, min")
        operation = input("Enter operation: ").strip().lower()

        if operation == "sum":
            print(f"Sum: {calculate_sum(numbers)}")
        elif operation == "average":
            print(f"Average: {calculate_average(numbers)}")
        elif operation == "max":
            print(f"Maximum: {find_maximum(numbers)}")
        elif operation == "min":
            print(f"Minimum: {find_minimum(numbers)}")
        else:
            print("Invalid operation.")
    except ValueError:
        print("Invalid input. Please enter numbers only.")
    except Exception:
        print("An unexpected error occurred.")

def main():
    main_math_operations()

if __name__ == "__main__":
    main()

Mathematical Operations
Enter a list of numbers separated by spaces: 1 2 33 56 6 7 77 88 
Choose an operation: sum, average, max, min
Enter operation: max
Maximum: 88.0


#4.2

1

In [18]:
def extract_every_other(lst):
    result = []
    for i in range(0, len(lst), 2):
        result.append(lst[i])
    return result

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_every_other(input_list)
print(output_list)

[1, 3, 5]


2

In [19]:
def get_sublist(lst, start, end):
    result = []
    for i in range(start, end):
        result.append(lst[i])
    return result

input_list = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(input_list, 2, 5)
print(sublist)

[3, 4, 5]


3

In [21]:
def reverse_list(lst):
    return lst[::-1]

input_list = [1, 2, 3, 4, 5]
reversed_list = reverse_list(input_list)
# print(reversed_list)

4

In [22]:
def remove_first_last(lst):
    return lst[1:-1]

input_list = [1, 2, 3, 4, 5, 6]
result_list = remove_first_last(input_list)
print(result_list)

[2, 3, 4, 5]


5

In [24]:
def get_first_n(lst, n):
    return lst[:n]

input_list = [1, 2, 3, 4, 5, 6, 7]
n = 4
result_list = get_first_n(input_list, n)
print(result_list)

[1, 2, 3, 4]


6

In [25]:
def get_last_n(lst, n):
    return lst[-n:]

input_list = [1, 2, 3, 4, 5]
n = 2
result_list = get_last_n(input_list, n)
print(result_list)

[4, 5]


7

In [26]:
def reverse_skip(lst):
    result = []
    for i in range(len(lst) - 2, -1, -2):
        result.append(lst[i])
    return result

input_list = [1, 2, 3, 4, 5, 6]
result_list = reverse_skip(input_list)
print(result_list)

[5, 3, 1]


#4.3

1

In [28]:
def flatten(lst):
    result = []
    for sublist in lst:
        for item in sublist:
            result.append(item)
    return result

input_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(input_list)
print(flattened_list)

[1, 2, 3, 4, 5]


2

In [29]:
def access_nested_element(lst, indices):
    element = lst
    for index in indices:
        element = element[index]
    return element

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(lst, indices)
print(result)

6


3

In [30]:
def sum_nested(lst):
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total

input_list = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(input_list)
print(result)

21


4

In [31]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):
            lst[i] = remove_element(lst[i], elem)
        elif elem == lst[i]:
            lst.pop(i)
            return remove_element(lst, elem)
    return lst

input_list = [[1, 2], [3, 2], [4, 5]]
elem_to_remove = 2
result = remove_element(input_list, elem_to_remove)
print(result)

[[1], [3], [4, 5]]


5

In [32]:
def find_max(lst):
    max_elem = 0

    for element in lst:
        if isinstance(element, list):
            max_elem = max(max_elem, find_max(element))
        else:
            max_elem = max(max_elem, element)

    return max_elem

input_list = [[1, 2], [3, [4, 5]], 6]
result = find_max(input_list)
print(result)

6


6

In [34]:
def count_occurrences(lst, elem):
    count = 0

    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1

    return count

input_list = [[1, 2], [2, 3], [2, 4]]
elem_to_count = 2
result = count_occurrences(input_list, elem_to_count)
print(result)

3


7

In [35]:
def deep_flatten(lst):
    flat_list = []

    for item in lst:
        if isinstance(item, list):
            flat_list.extend(deep_flatten(item))
        else:
            flat_list.append(item)

    return flat_list

input_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(input_list)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8

In [36]:
def average_nested(lst):
    total_sum = 0
    total_count = 0

    def flatten(lst):
        nonlocal total_sum, total_count
        for item in lst:
            if isinstance(item, list):
                flatten(item)
            else:
                total_sum += item
                total_count += 1

    flatten(lst)
    return total_sum / total_count if total_count != 0 else 0

input_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(input_list)
print(result)

3.5


#10.1

#Problem 1

# Task 1: Initialize an empty array with size 2x2

In [64]:
import numpy as np

empty_array = np.empty((2, 2))
print("Empty array (2x2):")
print(empty_array)

Empty array (2x2):
[[-2.    1.  ]
 [ 1.75 -0.75]]



# Task 2: Initialize an all one array with size 4x2

In [65]:
ones_array = np.ones((4, 2))
print("\nArray of ones (4x2):")
print(ones_array)


Array of ones (4x2):
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]




# Task 3: Return a new array of given shape and type, filled with fill value

In [66]:
shape = (3, 3)
fill_value = 7
filled_array = np.full(shape, fill_value)
print("\nArray filled with value 7 (3x3):")
print(filled_array)


Array filled with value 7 (3x3):
[[7 7 7]
 [7 7 7]
 [7 7 7]]




# Task 4: Return a new array of zeros with same shape and type as a given array

In [67]:
existing_array = np.array([1, 2, 3, 4])  # Existing array
zeros_array = np.zeros_like(existing_array)
print("\nArray of zeros with the same shape and type as existing array:")
print(zeros_array)


Array of zeros with the same shape and type as existing array:
[0 0 0 0]


# Task 5: Return a new array of ones with same shape and type as a given array

In [68]:
ones_like_array = np.ones_like(existing_array)
print("\nArray of ones with the same shape and type as existing array:")
print(ones_like_array)


Array of ones with the same shape and type as existing array:
[1 1 1 1]





# Task 6: Convert an existing list to a NumPy array

In [69]:
new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("\nNumPy array from list [1, 2, 3, 4]:")
print(array_from_list)


NumPy array from list [1, 2, 3, 4]:
[1 2 3 4]


#Problem 2

# Task 1: Create an array with values ranging from 10 to 49

In [70]:
import numpy as np

array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:")
print(array_10_to_49)

Array from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Task 2: Create a 3x3 matrix with values ranging from 0 to 8

In [71]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix with values from 0 to 8:")
print(matrix_3x3)


3x3 matrix with values from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Task 3: Create a 3x3 identity matrix

In [72]:
identity_matrix = np.eye(3)
print("\n3x3 identity matrix:")
print(identity_matrix)


3x3 identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Task 4: Create a random array of size 30 and find the mean of the array

In [73]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom array of size 30:")
print(random_array)
print("Mean of the random array:", mean_value)


Random array of size 30:
[0.92696488 0.81361329 0.29015157 0.23919034 0.72226123 0.06380515
 0.17938892 0.42380723 0.8360304  0.50673124 0.18640006 0.52820338
 0.21583466 0.55659777 0.04564099 0.96479644 0.19076225 0.09772582
 0.55113059 0.06975187 0.88185293 0.40753892 0.60613951 0.27363484
 0.90505588 0.46337802 0.16304753 0.02839188 0.71229373 0.44994149]
Mean of the random array: 0.443335426115585


# Task 5: Create a 10x10 array with random values and find the minimum and maximum values

In [74]:
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 array with random values:")
print(random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)


10x10 array with random values:
[[0.11559352 0.0381588  0.78228782 0.80312233 0.90053865 0.10070191
  0.39820543 0.81965794 0.85969202 0.77307045]
 [0.71636302 0.87338478 0.41910737 0.45963192 0.164135   0.37131184
  0.87577942 0.30962783 0.75675889 0.44607345]
 [0.97204658 0.5381964  0.44875058 0.24414021 0.18605372 0.53818068
  0.25086154 0.28874077 0.9065373  0.45978682]
 [0.10467215 0.86432023 0.46832315 0.94061929 0.40605808 0.83607195
  0.28446842 0.91283377 0.38910089 0.01418615]
 [0.56043239 0.8114436  0.41828925 0.28689151 0.15676663 0.0817532
  0.41015089 0.01219891 0.3989584  0.88312254]
 [0.55228733 0.07947439 0.31377778 0.96572132 0.23874474 0.81443264
  0.47491546 0.70440419 0.61255502 0.08149434]
 [0.30881472 0.7783936  0.87021329 0.12253731 0.49154158 0.56391712
  0.69948385 0.67649655 0.82109695 0.72645882]
 [0.18383071 0.87627989 0.70691006 0.87183544 0.49276891 0.94024373
  0.51988439 0.03658894 0.46490014 0.79267812]
 [0.44107825 0.63264349 0.14764231 0.9620809  0.

# Task 6: Create a zero array of size 10 and replace 5th element with 1

In [75]:
zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero array with 5th element replaced with 1:")
print(zero_array)


Zero array with 5th element replaced with 1:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Task 7: Reverse an array arr = [1, 2, 0, 0, 4, 0]

In [76]:
arr = [1, 2, 0, 0, 4, 0]
reversed_arr = arr[::-1]
print("\nReversed array:")
print(reversed_arr)


Reversed array:
[0, 4, 0, 0, 2, 1]


# Task 8: Create a 2D array with 1 on the border and 0 inside

In [77]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on the border and 0 inside:")
print(border_array)


2D array with 1 on the border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Task 9: Create an 8x8 matrix and fill it with a checkerboard pattern

In [78]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 checkerboard pattern:")
print(checkerboard)


8x8 checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem 3

# Task 1: Add the two arrays

In [79]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

add_arrays = x + y
print("Task 1: Sum of x and y:")
print(add_arrays)

Task 1: Sum of x and y:
[[ 6  8]
 [10 13]]


# Task 2: Subtract the two arrays

In [80]:
subtract_arrays = x - y
print("\nTask 2: Difference of x and y:")
print(subtract_arrays)


Task 2: Difference of x and y:
[[-4 -4]
 [-4 -3]]


# Task 3: Multiply the array with any integers of your choice (let's multiply by 2)

In [81]:
multiply_array = x * 2
print("\nTask 3: x multiplied by 2:")
print(multiply_array)


Task 3: x multiplied by 2:
[[ 2  4]
 [ 6 10]]


# Task 4: Find the square of each element of the array

In [82]:
square_elements = np.square(x)
print("\nTask 4: Square of each element in x:")
print(square_elements)


Task 4: Square of each element in x:
[[ 1  4]
 [ 9 25]]


# Task 5: Find the dot product between v and w, x and v, x and y

In [83]:
dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print("\nTask 5: Dot Products")
print("Dot product of v and w:", dot_v_w)
print("Dot product of x and v:", dot_x_v)
print("Dot product of x and y:", dot_x_y)


Task 5: Dot Products
Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: [[19 22]
 [50 58]]


# Task 6: Concatenate x and y along rows and concatenate v and w along columns

In [84]:
concat_x_y_row = np.concatenate((x, y), axis=0)
concat_v_w_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)

print("\nTask 6: Concatenation")
print("x and y concatenated along rows:")
print(concat_x_y_row)
print("v and w concatenated along columns:")
print(concat_v_w_col)


Task 6: Concatenation
x and y concatenated along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w concatenated along columns:
[[ 9 11]
 [10 12]]


# Task 7: Concatenate x and v; if you get an error, observe and explain why

In [85]:
try:
    concat_x_v = np.concatenate((x, v), axis=0)
    print("\nTask 7: Concatenate x and v:")
    print(concat_x_v)
except ValueError as e:
    print("\nTask 7 Error:", e)


Task 7 Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


#Problem 4

# Task 1: A * A^(-1) = I

In [86]:
# Given Matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("Task 1: A * A^(-1) = I:")
print(identity_matrix)

Task 1: A * A^(-1) = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


# Task 2: AB != BA

In [87]:
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nTask 2: AB and BA:")
print("AB:")
print(AB)
print("BA:")
print(BA)
are_equal = np.array_equal(AB, BA)
print("Are AB and BA equal?", are_equal)


Task 2: AB and BA:
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]
Are AB and BA equal? False


# Task 3: (AB)^T = B^T A^T

In [88]:
AB_transpose = np.transpose(AB)
BT_AT = np.dot(np.transpose(B), np.transpose(A))
print("\nTask 3: (AB)^T and B^T A^T:")
print("Transpose of AB:")
print(AB_transpose)
print("B^T * A^T:")
print(BT_AT)
are_equal_transposes = np.array_equal(AB_transpose, BT_AT)
print("Are (AB)^T and B^T * A^T equal?", are_equal_transposes)


Task 3: (AB)^T and B^T A^T:
Transpose of AB:
[[23 51]
 [13 29]]
B^T * A^T:
[[23 51]
 [13 29]]
Are (AB)^T and B^T * A^T equal? True


# Task 4: Solve the system of Linear equations using Inverse Method

In [89]:
A_matrix = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_vector = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A_matrix)
X = np.dot(A_inv, B_vector)
print("\nTask 4: Solving Linear Equation System using Inverse Method:")
print("Solution (x, y, z):")
print(X)


Task 4: Solving Linear Equation System using Inverse Method:
Solution (x, y, z):
[ 2.  1. -2.]


# Task 5: Solve the system of Linear equations using np.linalg.inv()

In [90]:
X_solution = np.linalg.inv(A_matrix).dot(B_vector)
print("\nTask 5: Solve using np.linalg.inv:")
print("Solution (x, y, z):")
print(X_solution)


Task 5: Solve using np.linalg.inv:
Solution (x, y, z):
[ 2.  1. -2.]


#10.2

# 1. Element-wise Addition

In [96]:
import time
import numpy as np

# Define the size
size = 1000000
matrix_size = 1000

# Using Python lists
list1 = [i for i in range(size)]
list2 = [i for i in range(size)]

start_time = time.time()
list_add = [list1[i] + list2[i] for i in range(size)]
python_list_add_time = time.time() - start_time
print(f"Element-wise addition using Python lists took: {python_list_add_time:.6f} seconds.")

# Using Numpy arrays
np_array1 = np.arange(size)
np_array2 = np.arange(size)

start_time = time.time()
np_array_add = np_array1 + np_array2
numpy_array_add_time = time.time() - start_time
print(f"Element-wise addition using NumPy arrays took: {numpy_array_add_time:.6f} seconds.")

Element-wise addition using Python lists took: 0.077117 seconds.
Element-wise addition using NumPy arrays took: 0.004452 seconds.


# 2. Element-wise Multiplication

In [97]:
# Using Python lists
start_time = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
python_list_mul_time = time.time() - start_time
print(f"Element-wise multiplication using Python lists took: {python_list_mul_time:.6f} seconds.")

# Using Numpy arrays
start_time = time.time()
np_array_mul = np_array1 * np_array2
numpy_array_mul_time = time.time() - start_time
print(f"Element-wise multiplication using NumPy arrays took: {numpy_array_mul_time:.6f} seconds.")

Element-wise multiplication using Python lists took: 0.087663 seconds.
Element-wise multiplication using NumPy arrays took: 0.005229 seconds.


# 3. Dot Product

In [98]:
# Using Python lists
start_time = time.time()
dot_product_python = sum(list1[i] * list2[i] for i in range(size))
python_dot_product_time = time.time() - start_time
print(f"Dot product using Python lists took: {python_dot_product_time:.6f} seconds.")

# Using Numpy arrays
start_time = time.time()
np_dot_product = np.dot(np_array1, np_array2)
numpy_dot_product_time = time.time() - start_time
print(f"Dot product using NumPy arrays took: {numpy_dot_product_time:.6f} seconds.")

Dot product using Python lists took: 0.132015 seconds.
Dot product using NumPy arrays took: 0.001895 seconds.


# 4. Matrix Multiplication

In [95]:
# Using Python lists
matrix1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]

start_time = time.time()
matrix_mul_python = [[sum(matrix1[i][k] * matrix2[k][j] for k in range(matrix_size)) for j in range(matrix_size)] for i in range(matrix_size)]
python_matrix_mul_time = time.time() - start_time
print(f"Matrix multiplication using Python lists took: {python_matrix_mul_time:.6f} seconds.")

# Using Numpy arrays
np_matrix1 = np.random.rand(matrix_size, matrix_size)
np_matrix2 = np.random.rand(matrix_size, matrix_size)

start_time = time.time()
matrix_mul_numpy = np.dot(np_matrix1, np_matrix2)
numpy_matrix_mul_time = time.time() - start_time
print(f"Matrix multiplication using NumPy arrays took: {numpy_matrix_mul_time:.6f} seconds.")

Matrix multiplication using Python lists took: 191.215912 seconds.
Matrix multiplication using NumPy arrays took: 0.066111 seconds.
